name: Release & Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Compile Extension
        run: npm run compile

      - name: Run Unit Tests
        run: npm run test

      - name: Publish to Open VSX Registry
        run: npm run publish:ovsx -- -p ${{ secrets.OVSX_PAT }}

      - name: Publish to VS Code Marketplace
        run: npm run publish:vsce -- -p ${{ secrets.VSCE_PAT }}
